#!/usr/bin/env python3
"""Build committed static blog pages from trusted, author-maintained Markdown."""
import argparse
from datetime import date
from html import escape
from html.parser import HTMLParser
import json
from pathlib import Path
import re
from string import Template
import sys
from urllib.parse import unquote, urlsplit

try:
    import markdown
except ImportError:
    sys.exit('Install the build dependency: python3 -m pip install -r blog/requirements.txt')

ROOT = Path(__file__).resolve().parent.parent
SITE = 'https://chrishornungmd.com'
MARKER = '<!-- Generated by blog/build_blog.py; edit Markdown or templates instead. -->'
REQUIRED = {'title', 'date', 'slug', 'description'}
OPTIONAL = {'original_url', 'original_note', 'social_image', 'social_image_alt'}
RESERVED = {'assets', 'posts', 'templates', 'tests', 'index'}
MONTHS = ('January February March April May June July August September October November December').split()


def parse_post(text):
    """Front matter is one key: JSON-string per line (a small YAML-compatible subset)."""
    lines = text.splitlines()
    if not lines or lines[0] != '---':
        raise ValueError('post must begin with --- front matter')
    try:
        end = lines.index('---', 1)
    except ValueError:
        raise ValueError('missing closing ---') from None
    meta = {}
    for number, line in enumerate(lines[1:end], 2):
        if not line.strip():
            continue
        key, separator, value = line.partition(':')
        if not separator or key not in REQUIRED | OPTIONAL or key in meta:
            raise ValueError(f'front matter line {number}: unknown, duplicate, or malformed key')
        try:
            value = json.loads(value.strip())
        except json.JSONDecodeError:
            raise ValueError(f'{key}: use a double-quoted JSON string') from None
        if not isinstance(value, str) or not value.strip() or any(ord(c) < 32 for c in value):
            raise ValueError(f'{key}: expected a nonempty, single-line string')
        meta[key] = value
    missing = REQUIRED - meta.keys()
    if missing:
        raise ValueError('missing fields: ' + ', '.join(sorted(missing)))
    if not re.fullmatch(r'[a-z0-9]+(?:-[a-z0-9]+)*', meta['slug']) or meta['slug'] in RESERVED:
        raise ValueError('slug must be lowercase words/numbers separated by hyphens, and not reserved')
    if not re.fullmatch(r'\d{4}-\d{2}-\d{2}', meta['date']):
        raise ValueError('date must be YYYY-MM-DD')
    date.fromisoformat(meta['date'])
    if 'original_url' in meta:
        url = urlsplit(meta['original_url'])
        if url.scheme != 'https' or not url.netloc:
            raise ValueError('original_url must be an absolute HTTPS URL')
    if 'original_note' in meta and 'original_url' not in meta:
        raise ValueError('original_note requires original_url')
    if 'social_image' in meta:
        value = meta['social_image']
        if not value.startswith('/') or value.startswith('//') or urlsplit(value).query or urlsplit(value).fragment:
            raise ValueError('social_image must be a root-relative local asset path')
    body = '\n'.join(lines[end + 1:]).strip()
    if not body:
        raise ValueError('post body must not be empty')
    return meta, body


def readable_date(value):
    day = date.fromisoformat(value)
    return f'{MONTHS[day.month - 1]} {day.day}, {day.year}'


def analytics(root):
    home = (root / 'index.html').read_text(encoding='utf-8')
    matches = re.findall(r'<!-- Cloudflare Web Analytics -->.*?<!-- End Cloudflare Web Analytics -->', home, re.S)
    if len(matches) != 1 or 'https://static.cloudflareinsights.com/beacon.min.js' not in matches[0] or 'data-cf-beacon=' not in matches[0]:
        raise ValueError('homepage must contain one marked Cloudflare Web Analytics beacon')
    return matches[0]


def template(root, name, **values):
    return Template((root / 'blog' / 'templates' / name).read_text(encoding='utf-8')).substitute(values)


def page(root, title, description, path, content, beacon, meta=None):
    canonical = SITE + path
    image = SITE + (meta or {}).get('social_image', '/social-card.png')
    image_alt = (meta or {}).get('social_image_alt', 'Chris Hornung, MD — Otolaryngology–Head & Neck Surgery.')
    extra = ''
    if meta:
        data = {'@context': 'https://schema.org', '@type': 'Article', 'headline': title,
                'description': description, 'datePublished': meta['date'], 'url': canonical,
                'mainEntityOfPage': canonical, 'image': image,
                'author': {'@type': 'Person', 'name': 'Chris Hornung, MD', 'url': SITE + '/'}}
        if 'original_url' in meta:
            data['isBasedOn'] = meta['original_url']
        serialized = json.dumps(data, ensure_ascii=False, sort_keys=True).replace('<', '\\u003c')
        extra = f'<meta property="article:published_time" content="{meta["date"]}">\n<script type="application/ld+json">{serialized}</script>'
    return template(root, 'page.html', marker=MARKER, title=escape(title + ' | Chris Hornung, MD'),
                    description=escape(description), canonical=canonical,
                    og_type='article' if meta else 'website', social_image=escape(image),
                    social_image_alt=escape(image_alt), extra_metadata=extra,
                    content=content, analytics=beacon)


class References(HTMLParser):
    def __init__(self):
        super().__init__()
        self.refs = []
        self.ids = set()
        self.beacons = []
        self.canonicals = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        if 'id' in attrs:
            self.ids.add(attrs['id'])
        for attribute in ('href', 'src'):
            if attrs.get(attribute):
                self.refs.append(attrs[attribute])
        if tag == 'meta' and attrs.get('property') in {'og:image'}:
            self.refs.append(attrs.get('content', ''))
        if tag == 'script' and 'cloudflareinsights.com' in attrs.get('src', ''):
            self.beacons.append(attrs)
        if tag == 'link' and attrs.get('rel') == 'canonical':
            self.canonicals.append(attrs.get('href'))
        if tag == 'img' and not attrs.get('alt', '').strip():
            raise ValueError('article images require descriptive alt text')

    handle_startendtag = handle_starttag


def validate(root, outputs, beacon):
    expected = References()
    expected.feed(beacon)
    if len(expected.beacons) != 1:
        raise ValueError('expected one homepage analytics script')
    json.loads(expected.beacons[0]['data-cf-beacon'])['token']
    for relative, html in outputs.items():
        parsed = References()
        parsed.feed(html)
        canonical = SITE + '/' + relative.removesuffix('index.html')
        if parsed.beacons != expected.beacons or parsed.canonicals != [canonical]:
            raise ValueError(f'{relative}: analytics or canonical validation failed')
        for ref in parsed.refs:
            url = urlsplit(ref)
            if url.scheme or url.netloc:
                if url.scheme not in {'https', 'http', 'mailto'}:
                    raise ValueError(f'{relative}: unsupported URL: {ref}')
                if url.netloc != urlsplit(SITE).netloc:
                    continue
            if not url.path:
                target = relative
            elif url.path.startswith('/') and not url.path.startswith('//'):
                target = unquote(url.path.lstrip('/'))
                if target.endswith('/') or not target:
                    target += 'index.html'
            else:
                raise ValueError(f'{relative}: use root-relative local links: {ref}')
            disk = (root / target).resolve()
            if root.resolve() not in disk.parents:
                raise ValueError(f'{relative}: path escapes site root: {ref}')
            if target not in outputs and not disk.is_file():
                raise ValueError(f'{relative}: missing local target: {ref}')
            if url.fragment:
                destination = References()
                destination.feed(outputs[target] if target in outputs else disk.read_text(encoding='utf-8'))
                if unquote(url.fragment) not in destination.ids:
                    raise ValueError(f'{relative}: missing anchor: {ref}')


def render_site(root=ROOT):
    beacon = analytics(root)
    posts = []
    slugs = set()
    for source in sorted((root / 'blog' / 'posts').glob('*.md')):
        try:
            meta, body = parse_post(source.read_text(encoding='utf-8'))
            if meta['slug'] in slugs:
                raise ValueError('duplicate slug: ' + meta['slug'])
            slugs.add(meta['slug'])
            posts.append((meta, body))
        except ValueError as error:
            raise ValueError(f'{source.name}: {error}') from error
    posts.sort(key=lambda post: (-date.fromisoformat(post[0]['date']).toordinal(), post[0]['slug']))
    outputs, cards = {}, []
    for meta, body in posts:
        path = '/blog/' + meta['slug'] + '/'
        note = ''
        if meta.get('original_url'):
            label = meta.get('original_note', 'Originally published elsewhere.')
            note = f'<p class="blog-origin">{escape(label)} <a href="{escape(meta["original_url"])}">Read the original article</a>.</p>'
        content = template(root, 'article.html', title=escape(meta['title']), date=meta['date'],
                           date_label=readable_date(meta['date']), origin=note,
                           body=markdown.markdown(body, extensions=['fenced_code', 'tables', 'attr_list'], output_format='html'))
        outputs[path.lstrip('/') + 'index.html'] = page(root, meta['title'], meta['description'], path, content, beacon, meta)
        cards.append(f'<li class="project blog-card"><p class="blog-date"><time datetime="{meta["date"]}">{readable_date(meta["date"])}</time></p>'
                     f'<h2><a href="{path}">{escape(meta["title"])}</a></h2><p>{escape(meta["description"])}</p>'
                     f'<a class="text-link" href="{path}">Read article <span aria-hidden="true">→</span></a></li>')
    content = template(root, 'index.html', posts='\n'.join(cards) or '<li>No posts yet.</li>')
    outputs['blog/index.html'] = page(root, 'Blog', 'Writing on medical education, clinical practice, and technology by Chris Hornung, MD.', '/blog/', content, beacon)
    validate(root, outputs, beacon)
    # Never silently delete old pages after a slug change/removal.
    stale = [p for p in (root / 'blog').glob('*/index.html') if MARKER in p.read_text(encoding='utf-8') and p.relative_to(root).as_posix() not in outputs]
    if stale:
        raise ValueError('orphaned generated pages; restore their source or intentionally remove/redirect them: ' + ', '.join(str(p) for p in stale))
    return outputs


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='validate and fail if committed HTML needs rebuilding; do not write')
    args = parser.parse_args()
    try:
        outputs = render_site()
        changed = []
        for relative, html in outputs.items():
            path = ROOT / relative
            if not path.exists() or path.read_text(encoding='utf-8') != html:
                changed.append(relative)
                if not args.check:
                    path.parent.mkdir(parents=True, exist_ok=True)
                    path.write_text(html, encoding='utf-8')
        if args.check and changed:
            raise ValueError('rebuild required: ' + ', '.join(changed))
        print(f'Validated {len(outputs)} blog pages; {len(changed)} ' + ('need updates.' if args.check else 'updated.'))
    except (ValueError, OSError, KeyError) as error:
        parser.exit(1, f'Blog build failed: {error}\n')


if __name__ == '__main__':
    main()
